name: Linter

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: npm install
        run: npm install # 検証として一旦すべて
      - name: eslint reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          eslint_flags: "src/"
      # - name: Run eslint
      #   run: npm run lint
